# Generated by Django 3.0.8 on 2021-01-19 14:00

from django.db import migrations


def remove_null_from_description_long(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        if place.description_long is None:
            place.description_long = ''
            place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_placeimage_number'),
    ]

    operations = [
        migrations.RunPython(remove_null_from_description_long),
    ]
