# Generated by Django 3.0.8 on 2021-01-20 12:19

from django.db import migrations


def remove_null_from_coordinates(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        if place.lng is None:
            place.lng = ''
            place.save()
        if place.lat is None:
            place.lat = ''
            place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20210119_1700'),
    ]

    operations = [
        migrations.RunPython(remove_null_from_coordinates),
    ]
