# Generated by Django 3.0.8 on 2021-01-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20210120_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='Номер'),
        ),
    ]
