# Generated by Django 3.0.8 on 2021-01-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20210129_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='number',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Номер'),
        ),
    ]
